Update Git Action

diff --git a/.github/workflows/run-tests-docker.yml b/.github/workflows/run-tests-docker.yml
--- a/.github/workflows/run-tests-docker.yml
+++ b/.github/workflows/run-tests-docker.yml
@@ -25,10 +25,14 @@ jobs:
           docker-compose up tests
           exit_code=$(docker inspect -f '{{.State.ExitCode}}' tests)
           echo $exit_code
+          if [ $TEST_EXIT_CODE -ne 0 ]; then
+            echo "Tests failed"
+            exit $TEST_EXIT_CODE
+          fi
 
       - name: Send Slack Success Notification
         uses: rtCamp/action-slack-notify@v2
-        if: ${{ $(docker inspect -f '{{.State.ExitCode}}' tests) ==0 }}
+        if: ${{ success() }}
         env:
           SLACK_CHANNEL: general
           SLACK_COLOR: 'bad' # or a specific color like 'good' or '#ff00ff'
@@ -41,7 +45,7 @@ jobs:
 
       - name: Send Slack Failure Notification
         uses: rtCamp/action-slack-notify@v2
-        if: ${{ $(docker inspect -f '{{.State.ExitCode}}' tests) ==1 }}
+        if: ${{ failure() }}
         env:
           SLACK_CHANNEL: general
           SLACK_COLOR: 'good' # or a specific color like 'good' or '#ff00ff'
