Update Git Action

diff --git a/.github/workflows/run-tests-docker.yml b/.github/workflows/run-tests-docker.yml
--- a/.github/workflows/run-tests-docker.yml
+++ b/.github/workflows/run-tests-docker.yml
@@ -23,7 +23,12 @@ jobs:
         id: tests
         run: |
           docker-compose up tests
-          TEST_EXIT_CODE=$?
+          exit_code=$?
+          if [ $exit_code -eq 0 ]; then
+          echo "Tests passed!"
+          else
+          echo "Tests failed!"
+          fi
 
       - name: Close Containers
         run: docker-compose down
